version: '2'
services:
    fundunivers-app:
        image: fundunivers
        external_links:
            - fundunivers-mysql:mysql
            - fundunivers-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fundunivers?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    fundunivers-mysql:
        extends:
            file: mysql.yml
            service: fundunivers-mysql
    fundunivers-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: fundunivers-elasticsearch
